# top = '.'
# out = 'build'

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')
def build(bld):
    bld.program(
        features     = ['cxx','cprogram'],
        source       = ['src/main.C',
                        'src/FACElastic/FACElastic.C',
                        'src/FACElastic/fix_moduli.C',
                        'src/FACElastic/applyGradientDetector.C',
                        'src/FACElastic/initializeLevelData.C',
                        'src/FACElastic/packDerivedDataIntoDoubleBuffer.C',
                        'src/FACElastic/resetHierarchyConfiguration.C',
                        'src/FACElastic/setupPlotter.C',
                        'src/FACElastic/solveElastic.C',
                        'src/P_Refine.C',
                        'src/V_Refine/refine.C',
                        'src/V_Refine/refine_along_line.C',
                        'src/Resid_Coarsen.C',
                        'src/V_Coarsen/coarsen_2D.C',
                        'src/V_Coarsen/coarsen_3D.C',
                        'src/P_Boundary_Refine/refine.C',
                        'src/P_Boundary_Refine/Update_P_2D.C',
                        'src/P_Boundary_Refine/Update_P_3D.C',
                        'src/V_Boundary_Refine/refine.C',
                        'src/V_Boundary_Refine/Update_V_2D.C',
                        'src/V_Boundary_Refine/Update_V_3D.C',
                        'src/V_Coarsen_Patch_Strategy/postprocessCoarsen_2D.C',
                        'src/V_Coarsen_Patch_Strategy/postprocessCoarsen_3D.C',
                        'src/set_boundary.C',
                        'src/ElasticFACOps/ElasticFACOps.C',
                        'src/ElasticFACOps/computeCompositeResidualOnLevel.C',
                        'src/ElasticFACOps/residual_2D.C',
                        'src/ElasticFACOps/residual_3D.C',
                        'src/ElasticFACOps/computeResidualNorm.C',
                        'src/ElasticFACOps/computeVectorWeights.C',
                        'src/ElasticFACOps/deallocateOperatorState.C',
                        'src/ElasticFACOps/finalizeCallback.C',
                        'src/ElasticFACOps/initializeOperatorState.C',
                        'src/ElasticFACOps/postprocessOneCycle.C',
                        'src/ElasticFACOps/prolongErrorAndCorrect.C',
                        'src/ElasticFACOps/restrictResidual.C',
                        'src/ElasticFACOps/restrictSolution.C',
                        'src/ElasticFACOps/smoothError.C',
                        'src/ElasticFACOps/smooth_Tackley_2D.C',
                        'src/ElasticFACOps/smooth_Tackley_3D.C',
                        'src/ElasticFACOps/set_boundaries.C',
                        'src/ElasticFACOps/solveCoarsestLevel.C',
                        'src/ElasticFACOps/solveCoarsestLevel_HYPRE.C',
                        'src/ElasticFACOps/smooth_V_2D.C',
                        'src/ElasticFACOps/smooth_V_3D.C',
                        'src/ElasticFACOps/xeqScheduleGhostFill.C',
                        'src/ElasticFACOps/xeqScheduleGhostFillNoCoarse.C',
                        'src/ElasticFACOps/xeqScheduleProlongation.C',
                        'src/ElasticFACOps/xeqScheduleRRestriction.C',
                        'src/ElasticFACOps/xeqScheduleURestriction.C',
                        'src/ElasticFACSolver/ElasticFACSolver.C',
                        'src/ElasticFACSolver/ElasticFACSolver_Destructor.C',
                        'src/ElasticFACSolver/createVectorWrappers.C',
                        'src/ElasticFACSolver/deallocateSolverState.C',
                        'src/ElasticFACSolver/destroyVectorWrappers.C',
                        'src/ElasticFACSolver/enableLogging.C',
                        'src/ElasticFACSolver/getFromInput.C',
                        'src/ElasticFACSolver/initializeSolverState.C',
                        'src/ElasticFACSolver/initializeStatics.C',
                        'src/ElasticFACSolver/setBcObject.C',
                        'src/ElasticFACSolver/setBoundaries.C',
                        'src/ElasticFACSolver/solveSystem.C',
                        'src/ElasticHypreSolver.C'],

        target       = 'gamra',
        cxxflags      = ['-O3', '-Wall', '-Wextra', '-Wconversion',
                        '-DTESTING=0', '-Drestrict='],
        # cxxflags      = ['-g', '-Wall', '-Wextra', '-Wconversion',
        #                  '-Drestrict='],
        lib          = ['SAMRAI_appu', 'SAMRAI_algs', 'SAMRAI_solv',
                        'SAMRAI_geom', 'SAMRAI_mesh', 'SAMRAI_math',
                        'SAMRAI_pdat', 'SAMRAI_xfer', 'SAMRAI_hier',
                        'SAMRAI_tbox', 'petsc', 'hdf5',
                        'HYPRE',
                        'HYPRE_sstruct_ls', 'HYPRE_sstruct_mv',
                        'HYPRE_struct_ls', 'HYPRE_struct_mv',
                        'HYPRE_parcsr_ls',
                        'HYPRE_DistributedMatrixPilutSolver',
                        'HYPRE_ParaSails', 'HYPRE_Euclid',
                        'HYPRE_MatrixMatrix', 'HYPRE_DistributedMatrix',
                        'HYPRE_IJ_mv', 'HYPRE_parcsr_mv', 'HYPRE_seq_mv',
                        'HYPRE_krylov', 'HYPRE_utilities', 'hdf5',
                        'dl', 'm', 'gfortranbegin', 'gfortran', 'm',
                        'gfortranbegin', 'gfortran', 'm', 'gfortranbegin',
                        'gfortran', 'm'],
        libpath      = ['/home/boo/cig/SAMRAI-hg-build/lib',
                        '/usr/lib/petsc/linux-gnu-c-opt/lib'],
        # libpath      = ['/Users/sbarbot/Documents/src/samrai/lib',
        #                 '/Users/sbarbot/Documents/src/petsc/petsc-3.2-p7/real8-with-debug/lib',
        #                 '/sw/lib',
        #                 '/sw/lib/gcc4.6/lib/gcc/x86_64-apple-darwin10.8.0/4.6.1',
        #                 '/sw/lib/gcc4.6/lib',
        #                 '/shared/lib'],
        includes = ['src','src/FTensor','../../SAMRAI-hg-build/include',
                    '../../SAMRAI-hg/source',
                    '/usr/lib/petsc/include',
                    '/usr/lib/petsc/bmake/linux-gnu-c-opt',
                    '/usr/lib/petsc/src/vec',
                    '/usr/include']
        # includes = ['src','../../samrai/include',
        #             '../../samrai/source',
        #             '../../petsc/petsc-3.2-p7/real8-with-debug/include',
        #             '/usr/lib/petsc/bmake/linux-gnu-c-opt',
        #             '../../petsc/petsc-3.2-p7/src/vec',
        #             '/usr/include']
        )
